# .streamlit/secrets.toml
[firebase]
key_file_path = "playgroundcalender-e20f5-firebase-adminsdk-fbsvc-5b601edca4.json"

# --- Admin Password ---
[admin]
password = "Hayashicho" # 管理者モードに入るためのパスワード（自由に変更してください）